# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(353, 464)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 115))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ModificarArista = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ModificarArista.setObjectName("ModificarArista")
        self.verticalLayout.addWidget(self.ModificarArista)
        self.labelOrigen = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelOrigen.setObjectName("labelOrigen")
        self.verticalLayout.addWidget(self.labelOrigen)
        self.lineEditOrigenModficar = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditOrigenModficar.setObjectName("lineEditOrigenModficar")
        self.verticalLayout.addWidget(self.lineEditOrigenModficar)
        self.labelDestinoModificar = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelDestinoModificar.setObjectName("labelDestinoModificar")
        self.verticalLayout.addWidget(self.labelDestinoModificar)
        self.lineEditDestinoModificar = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditDestinoModificar.setObjectName("lineEditDestinoModificar")
        self.verticalLayout.addWidget(self.lineEditDestinoModificar)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 10, 160, 115))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.InvertirArista = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.InvertirArista.setObjectName("InvertirArista")
        self.verticalLayout_2.addWidget(self.InvertirArista)
        self.labelOrigenInvertir = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labelOrigenInvertir.setObjectName("labelOrigenInvertir")
        self.verticalLayout_2.addWidget(self.labelOrigenInvertir)
        self.lineEditOrigenInvertir = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditOrigenInvertir.setObjectName("lineEditOrigenInvertir")
        self.verticalLayout_2.addWidget(self.lineEditOrigenInvertir)
        self.labelDestinoInvertir = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labelDestinoInvertir.setObjectName("labelDestinoInvertir")
        self.verticalLayout_2.addWidget(self.labelDestinoInvertir)
        self.lineEditDestinoInvertir = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditDestinoInvertir.setObjectName("lineEditDestinoInvertir")
        self.verticalLayout_2.addWidget(self.lineEditDestinoInvertir)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 150, 160, 250))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.CrearBarrio = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.CrearBarrio.setObjectName("CrearBarrio")
        self.verticalLayout_3.addWidget(self.CrearBarrio)
        self.labelPunto1 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.labelPunto1.setObjectName("labelPunto1")
        self.verticalLayout_3.addWidget(self.labelPunto1)
        self.lineEditPunto1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEditPunto1.setObjectName("lineEditPunto1")
        self.verticalLayout_3.addWidget(self.lineEditPunto1)
        self.labelPunto2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.labelPunto2.setObjectName("labelPunto2")
        self.verticalLayout_3.addWidget(self.labelPunto2)
        self.lineEditPunto2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEditPunto2.setObjectName("lineEditPunto2")
        self.verticalLayout_3.addWidget(self.lineEditPunto2)
        self.labelPunto3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.labelPunto3.setObjectName("labelPunto3")
        self.verticalLayout_3.addWidget(self.labelPunto3)
        self.lineEditPunto3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEditPunto3.setObjectName("lineEditPunto3")
        self.verticalLayout_3.addWidget(self.lineEditPunto3)
        self.labelPunto4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.labelPunto4.setObjectName("labelPunto4")
        self.verticalLayout_3.addWidget(self.labelPunto4)
        self.lineEditPunto4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEditPunto4.setObjectName("lineEditPunto4")
        self.verticalLayout_3.addWidget(self.lineEditPunto4)
        self.nombreBarrio = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.nombreBarrio.setObjectName("nombreBarrio")
        self.verticalLayout_3.addWidget(self.nombreBarrio)
        self.lineEditNombreBarrio = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEditNombreBarrio.setObjectName("lineEditNombreBarrio")
        self.verticalLayout_3.addWidget(self.lineEditNombreBarrio)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(180, 230, 160, 25))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.floydWarshall = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.floydWarshall.setObjectName("floydWarshall")
        self.verticalLayout_4.addWidget(self.floydWarshall)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(180, 150, 160, 71))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.agregarBarrio = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.agregarBarrio.setObjectName("agregarBarrio")
        self.verticalLayout_5.addWidget(self.agregarBarrio)
        self.labelNombretanque = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.labelNombretanque.setObjectName("labelNombretanque")
        self.verticalLayout_5.addWidget(self.labelNombretanque)
        self.lineEditNombreTanque = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.lineEditNombreTanque.setObjectName("lineEditNombreTanque")
        self.verticalLayout_5.addWidget(self.lineEditNombreTanque)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(180, 260, 160, 115))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.InvertirArista_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.InvertirArista_2.setObjectName("InvertirArista_2")
        self.verticalLayout_6.addWidget(self.InvertirArista_2)
        self.labelOrigenInvertir_2 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.labelOrigenInvertir_2.setObjectName("labelOrigenInvertir_2")
        self.verticalLayout_6.addWidget(self.labelOrigenInvertir_2)
        self.lineEditOrigenInvertir_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEditOrigenInvertir_2.setObjectName("lineEditOrigenInvertir_2")
        self.verticalLayout_6.addWidget(self.lineEditOrigenInvertir_2)
        self.labelDestinoInvertir_2 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.labelDestinoInvertir_2.setObjectName("labelDestinoInvertir_2")
        self.verticalLayout_6.addWidget(self.labelDestinoInvertir_2)
        self.lineEditDestinoInvertir_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEditDestinoInvertir_2.setObjectName("lineEditDestinoInvertir_2")
        self.verticalLayout_6.addWidget(self.lineEditDestinoInvertir_2)
        self.Actualizar = QtWidgets.QPushButton(self.centralwidget)
        self.Actualizar.setGeometry(QtCore.QRect(220, 390, 75, 23))
        self.Actualizar.setObjectName("Actualizar")
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.verticalLayoutWidget_4.raise_()
        self.verticalLayoutWidget_5.raise_()
        self.floydWarshall.raise_()
        self.verticalLayoutWidget_6.raise_()
        self.Actualizar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 353, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ModificarArista.setText(_translate("MainWindow", "Modificar Estado Arista"))
        self.labelOrigen.setText(_translate("MainWindow", "Origen"))
        self.labelDestinoModificar.setText(_translate("MainWindow", "Destino"))
        self.InvertirArista.setText(_translate("MainWindow", "Invertir Arista"))
        self.labelOrigenInvertir.setText(_translate("MainWindow", "Origen"))
        self.labelDestinoInvertir.setText(_translate("MainWindow", "Destino"))
        self.CrearBarrio.setText(_translate("MainWindow", "Crear Barrio"))
        self.labelPunto1.setText(_translate("MainWindow", "Punto 1."))
        self.labelPunto2.setText(_translate("MainWindow", "Punto 2."))
        self.labelPunto3.setText(_translate("MainWindow", "Punto 3."))
        self.labelPunto4.setText(_translate("MainWindow", "Punto 4."))
        self.nombreBarrio.setText(_translate("MainWindow", "Nombre"))
        self.floydWarshall.setText(_translate("MainWindow", "Buscar caminos"))
        self.agregarBarrio.setText(_translate("MainWindow", "Agregar Barrio"))
        self.labelNombretanque.setText(_translate("MainWindow", "Nombre del Tanque"))
        self.InvertirArista_2.setText(_translate("MainWindow", "Generar Obstrucción"))
        self.labelOrigenInvertir_2.setText(_translate("MainWindow", "Origen"))
        self.labelDestinoInvertir_2.setText(_translate("MainWindow", "Destino"))
        self.Actualizar.setText(_translate("MainWindow", "Actualizar"))

